require: rubocop-rails

AllCops:
    Exclude:
        - 'app/channels/*'
        - 'app/helpers/application_helper.rb'
        - 'app/models/application_record.rb'
        - 'bin/**/*'
        - 'config.ru'
        - 'config/**/*'
        - 'db/**/*'
        - 'spec/rails_helper.rb'
        - 'Gemfile'
        - 'Rakefile'

Metrics/AbcSize:
    Max: 20

Metrics/BlockLength:
    Exclude:
        - 'spec/**/*'

Metrics/MethodLength:
    Max: 15

Style/FrozenStringLiteralComment:
    Enabled: false
